//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scraper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scraper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;code&quot;:200,&quot;status&quot;:&quot;Success&quot;,&quot;data&quot;:{&quot;count&quot;:4271,&quot;publishers&quot;:{&quot;1&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Microsoft Studios&quot;},&quot;2&quot;:{&quot;id&quot;:2,&quot;name&quot;:&quot;Electronic Arts&quot;},&quot;3&quot;:{&quot;id&quot;:3,&quot;name&quot;:&quot;Nintendo&quot;},&quot;4&quot;:{&quot;id&quot;:4,&quot;name&quot;:&quot;Bally Mfg. Corp.&quot;},&quot;6&quot;:{&quot;id&quot;:6,&quot;name&quot;:&quot;Bandai Namco Entertainment&quot;},&quot;7&quot;:{&quot;id&quot;:7,&quot;name&quot;:&quot;Ubisoft Entertainment&quot;},&quot;8&quot;:{&quot;id&quot;:8,&quot;name&quot;:&quot;2K Games&quot;},&quot;9&quot;:{&quot;id&quot;:9,&quot;name&quot;:&quot;Capcom&quot;},&quot;11&quot;:{&quot;id&quot;:11,&quot;name&quot;:&quot;Squaresoft&quot;},&quot;12&quot;:{&quot;id&quot;:12,&quot;name&quot;:&quot;Square Enix&quot;},&quot;13&quot;:{&quot;id&quot;:13,&quot;name&quot;:&quot;Valve Corporation&quot;},&quot;14&quot;:{&quot;id&quot;:14,&quot;n....
        /// </summary>
        internal static string PublisherJson {
            get {
                return ResourceManager.GetString("PublisherJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ss {
            get {
                object obj = ResourceManager.GetObject("ss", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tgdb {
            get {
                object obj = ResourceManager.GetObject("tgdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///&quot;code&quot;: 200,
        ///&quot;status&quot;: &quot;Success&quot;,
        ///&quot;data&quot;: {
        ///  &quot;count&quot;: 109,
        ///  &quot;platforms&quot;: {
        ///	&quot;1&quot;: {
        ///	  &quot;id&quot;: 1,
        ///	  &quot;name&quot;: &quot;PC&quot;,
        ///	  &quot;alias&quot;: &quot;pc&quot;,
        ///	  &quot;icon&quot;: &quot;pc-1336524756.png&quot;,
        ///	  &quot;console&quot;: &quot;1.png&quot;,
        ///	  &quot;controller&quot;: &quot;&quot;,
        ///	  &quot;developer&quot;: &quot;IBM&quot;
        ///	},
        ///	&quot;2&quot;: {
        ///	  &quot;id&quot;: 2,
        ///	  &quot;name&quot;: &quot;Nintendo GameCube&quot;,
        ///	  &quot;alias&quot;: &quot;nintendo-gamecube&quot;,
        ///	  &quot;icon&quot;: &quot;nintendo-gamecube-1336524714.png&quot;,
        ///	  &quot;console&quot;: &quot;2.png&quot;,
        ///	  &quot;controller&quot;: &quot;2.png&quot;,
        ///	  &quot;developer&quot;: &quot;Nintendo&quot;
        ///	},
        ///	&quot;3&quot;: {
        ///	  &quot;id&quot;: 3,
        ///	  &quot;name&quot;: &quot;Ninten [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TGDBPlatformJson {
            get {
                return ResourceManager.GetString("TGDBPlatformJson", resourceCulture);
            }
        }
    }
}
